<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
    <AssemblyName>SecureIntegration.Broker.Sdk</AssemblyName>
    <RootNamespace>SecureIntegration.Broker.Sdk</RootNamespace>
    <IsPackable>true</IsPackable>
    <PackageId>SecureIntegration.Broker.Sdk</PackageId>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);IncludePrivateProjectReferenceAssemblies</TargetsForTfmSpecificBuildOutput>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Shared/SecureIntegration.Contracts/SecureIntegration.Contracts.csproj">
      <PrivateAssets Condition="'$(AlphaReleasePack)' == 'true'">all</PrivateAssets>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../../LICENSE-APACHE-2.0" Pack="true" PackagePath="" />
    <None Include="../../../NOTICE" Pack="true" PackagePath="" />
  </ItemGroup>
  <Target Name="IncludePrivateProjectReferenceAssemblies" DependsOnTargets="BuildOnlySettings;ResolveReferences">
    <ItemGroup>
      <BuildOutputInPackage Include="@(ReferenceCopyLocalPaths-&gt;WithMetadataValue('ReferenceSourceTarget', 'ProjectReference'))" />
    </ItemGroup>
  </Target>
</Project>
