<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>SecureIntegration.M3.LegacySimulator</AssemblyName>
    <RootNamespace>SecureIntegration.M3.LegacySimulator</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../sdk/dotnet/Broker.Sdk/Broker.Sdk.csproj" />
  </ItemGroup>
</Project>
