/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/enrollments/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createEnrollmentChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/enrollments:activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activateInstallation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/enrollments:renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["renewInstallationCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/broker-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBrokerPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connectors/{connectorId}/operations/{operationId}:invoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["invokeConnectorOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/connectors:validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateConnectorDefinition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/connectors:import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importConnectorDefinition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConnectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/connectors/{connectorId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConnectorVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/connectors/{connectorId}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["showConnectorVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/connectors/{connectorId}/versions/{version}:export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exportConnectorVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/connectors/{connectorId}/versions/{version}:validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateStoredConnectorVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/connectors/{connectorId}/versions/{version}:publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishConnectorVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/connectors/{connectorId}/versions/{version}:retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retireConnectorVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/connectors/{connectorId}:rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rollbackConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/connectors/{connectorId}/bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putConnectorBindings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/connectors/{connectorId}:test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testPublishedConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTenants"];
        put?: never;
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApplications"];
        put?: never;
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEnvironments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/installations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInstallations"];
        put?: never;
        post: operations["createInstallation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGrants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminConnectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Process alive. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Required dependencies ready. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AdminRole: "Viewer" | "ConnectorEditor" | "ConnectorApprover" | "Operator" | "SecurityAdministrator";
        AdminSession: {
            /** Format: uuid */
            id: string;
            displayName: string;
            roles: {
                role: components["schemas"]["AdminRole"];
                /** Format: uuid */
                tenantId?: string | null;
            }[];
        };
        Dashboard: {
            tenants: number;
            applications: number;
            /** @enum {string} */
            database: "healthy" | "unhealthy";
            /** @enum {string} */
            provider: "healthy" | "unhealthy";
            /** Format: date-time */
            generatedAtUtc: string;
        };
        Page: {
            items: unknown[];
            offset: number;
            limit: number;
            total: number;
        };
        Tenant: {
            /** Format: uuid */
            id: string;
            code: string;
            displayName: string;
            status: string;
            /** Format: date-time */
            createdAt: string;
        };
        TenantPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Tenant"][];
        };
        CreateTenant: {
            code: string;
            displayName: string;
        };
        Application: {
            /** Format: uuid */
            id: string;
            code: string;
            displayName: string;
            status: string;
            minimumBrokerVersion: string;
            maximumBrokerVersion?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ApplicationPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Application"][];
        };
        CreateApplication: {
            code: string;
            displayName: string;
            minimumBrokerVersion: string;
            maximumBrokerVersion?: string | null;
        };
        Environment: {
            /** Format: uuid */
            id: string;
            code: string;
            displayName: string;
            productionControls: boolean;
        };
        EnvironmentPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Environment"][];
        };
        Installation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            applicationId: string;
            /** Format: uuid */
            environmentId: string;
            status: string;
            brokerVersion?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastSeenAt?: string | null;
        };
        InstallationPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Installation"][];
        };
        CreateInstallation: {
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            applicationId: string;
            /** Format: uuid */
            environmentId: string;
        };
        ProvisionedActivation: {
            /** Format: uuid */
            installationId: string;
            /** Format: uuid */
            activationCodeId: string;
            activationCode: string;
            /** Format: date-time */
            expiresAt: string;
        };
        Grant: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            installationId: string;
            /** Format: uuid */
            tenantId: string;
            connectorId: string;
            operationId: string;
            enabled: boolean;
            /** Format: date-time */
            validFrom: string;
            /** Format: date-time */
            validUntil?: string | null;
        };
        GrantPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Grant"][];
        };
        AuditEvent: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            occurredAt: string;
            action: string;
            targetType: string;
            targetId: string;
            /** Format: uuid */
            correlationId: string;
            outcome: string;
            reasonCode: string;
        };
        AuditPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["AuditEvent"][];
        };
        ConnectorSummary: {
            connectorId: string;
            displayName: string;
            versions: number;
            publishedVersion?: string | null;
            publicationRevision: number;
        };
        InvokeRequest: {
            /** Format: uuid */
            correlationId: string;
            payload: string;
            contentType?: string;
            headers?: {
                [key: string]: string;
            };
        };
        ConnectorImportRequest: {
            definition: Record<string, never>;
            expectedChecksumSha256?: string | null;
        };
        VersionActionRequest: {
            expectedRowVersion: number;
            expectedPublicationRevision?: number | null;
        };
        RollbackRequest: {
            targetVersion: string;
            expectedActiveRowVersion: number;
        };
        Problem: {
            status: number;
            code: string;
            /** Format: uuid */
            correlationId?: string;
        };
    };
    responses: {
        /** @description Redacted stable error. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ConnectorId: string;
        OperationId: string;
        Version: string;
        TenantId: string;
        Offset: number;
        Limit: number;
    };
    requestBodies: {
        ConnectorImport: {
            content: {
                "application/json": components["schemas"]["ConnectorImportRequest"];
            };
        };
        VersionAction: {
            content: {
                "application/json": components["schemas"]["VersionActionRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createEnrollmentChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Short-lived enrollment challenge. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    activateInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Installation enrolled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    renewInstallationCredential: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Installation credential renewed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getBrokerPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Broker compatibility policy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    invokeConnectorOperation: {
        parameters: {
            query?: never;
            header: {
                "X-BG-Timestamp": string;
                "X-BG-Nonce": string;
                "X-BG-Content-SHA256": string;
                "X-BG-Signature": string;
                traceparent: string;
            };
            path: {
                connectorId: components["parameters"]["ConnectorId"];
                operationId: components["parameters"]["OperationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvokeRequest"];
            };
        };
        responses: {
            /** @description Sanitized connector response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    validateConnectorDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ConnectorImport"];
        responses: {
            /** @description Validation result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    importConnectorDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ConnectorImport"];
        responses: {
            /** @description Draft created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listConnectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redacted Connector list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listConnectorVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: components["parameters"]["ConnectorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connector versions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    showConnectorVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: components["parameters"]["ConnectorId"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version metadata without bindings or secret references. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    exportConnectorVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: components["parameters"]["ConnectorId"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical Connector JSON without Environment bindings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    validateStoredConnectorVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: components["parameters"]["ConnectorId"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["VersionAction"];
        responses: {
            /** @description Version validated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    publishConnectorVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: components["parameters"]["ConnectorId"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["VersionAction"];
        responses: {
            /** @description Version published atomically. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    retireConnectorVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: components["parameters"]["ConnectorId"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["VersionAction"];
        responses: {
            /** @description Version retired. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    rollbackConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: components["parameters"]["ConnectorId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollbackRequest"];
            };
        };
        responses: {
            /** @description Previously Published version reactivated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    putConnectorBindings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: components["parameters"]["ConnectorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-side binding revision updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    testPublishedConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: components["parameters"]["ConnectorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published definition and bindings resolve without invocation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getAdminSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current redacted principal and roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSession"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getCsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Opaque anti-CSRF request token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
        };
    };
    logoutAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session invalidated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getAdminDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider-neutral status summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listTenants: {
        parameters: {
            query?: {
                offset?: components["parameters"]["Offset"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenant"];
            };
        };
        responses: {
            /** @description Tenant created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listApplications: {
        parameters: {
            query?: {
                offset?: components["parameters"]["Offset"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplication"];
            };
        };
        responses: {
            /** @description Application created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listEnvironments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environment page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listInstallations: {
        parameters: {
            query: {
                tenantId: components["parameters"]["TenantId"];
                offset?: components["parameters"]["Offset"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Installation page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallationPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInstallation"];
            };
        };
        responses: {
            /** @description One-time activation response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvisionedActivation"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listGrants: {
        parameters: {
            query: {
                tenantId: components["parameters"]["TenantId"];
                offset?: components["parameters"]["Offset"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grant page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listAudit: {
        parameters: {
            query: {
                tenantId: components["parameters"]["TenantId"];
                offset?: components["parameters"]["Offset"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redacted audit page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listAdminConnectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connector summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorSummary"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
