targetScope = 'resourceGroup'

@description('Short lowercase prefix used for globally unique dev resources.')
@minLength(3)
@maxLength(10)
param prefix string

@description('Azure region for the ephemeral M3B environment.')
param location string = resourceGroup().location

@description('Full immutable Gateway image reference, preferably registry/repository@sha256:digest.')
param gatewayImageReference string

@description('Full immutable vendor mock image reference.')
param vendorImageReference string

@description('OIDC deployment principal object ID, used only for scoped ACR push and synthetic secret provisioning.')
param deploymentPrincipalObjectId string

@secure()
@description('Ephemeral PostgreSQL administrator password generated by the workflow.')
param postgresAdministratorPassword string

@secure()
@description('Synthetic vendor API key expected by the mock.')
param vendorApiKey string

@secure()
@description('Synthetic vendor control token used only by the smoke runner.')
param vendorControlToken string

@description('Public thumbprint of the synthetic outbound client certificate.')
param vendorClientThumbprint string

var suffix = uniqueString(resourceGroup().id)
var compact = toLower('${prefix}${suffix}')
var acrName = take('${compact}acr', 50)
var vaultName = take('${compact}kv', 24)
var identityName = take('${compact}-gateway-mi', 128)
var planName = take('${compact}-plan', 40)
var gatewayName = take('${compact}-gateway', 60)
var vendorName = take('${compact}-vendor', 60)
var postgresName = take('${compact}-pg18', 63)
var logName = take('${compact}-logs', 63)
var insightsName = take('${compact}-insights', 255)
var keyVaultSecretsUserRole = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '4633458b-17de-408a-b874-0445c86b69e6')
var keyVaultSecretsOfficerRole = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'b86a8fe4-44ce-4948-aee5-eccb2c155cd7')
var acrPullRole = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '7f951dda-4ed3-4680-a7ca-43fe172d538d')
var acrPushRole = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '8311e382-0749-4cb8-b61a-304f252e45ec')

resource logs 'Microsoft.OperationalInsights/workspaces@2025-02-01' = {
  name: logName
  location: location
  properties: {
    retentionInDays: 30
    sku: { name: 'PerGB2018' }
    features: {
      enableLogAccessUsingOnlyResourcePermissions: true
    }
  }
}

resource insights 'Microsoft.Insights/components@2020-02-02' = {
  name: insightsName
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: logs.id
    DisableIpMasking: false
  }
}

resource identity 'Microsoft.ManagedIdentity/userAssignedIdentities@2024-11-30' = {
  name: identityName
  location: location
}

resource registry 'Microsoft.ContainerRegistry/registries@2025-11-01' = {
  name: acrName
  location: location
  sku: { name: 'Basic' }
  properties: {
    adminUserEnabled: false
    anonymousPullEnabled: false
    publicNetworkAccess: 'Enabled'
    policies: {
      retentionPolicy: { days: 7, status: 'enabled' }
    }
  }
}

resource registryPull 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(registry.id, identity.id, acrPullRole)
  scope: registry
  properties: {
    principalId: identity.properties.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: acrPullRole
  }
}

resource registryPush 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(registry.id, deploymentPrincipalObjectId, acrPushRole)
  scope: registry
  properties: {
    principalId: deploymentPrincipalObjectId
    principalType: 'ServicePrincipal'
    roleDefinitionId: acrPushRole
  }
}

resource vault 'Microsoft.KeyVault/vaults@2025-05-01' = {
  name: vaultName
  location: location
  properties: {
    tenantId: subscription().tenantId
    sku: { family: 'A', name: 'standard' }
    enableRbacAuthorization: true
    enablePurgeProtection: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 7
    publicNetworkAccess: 'Enabled'
    networkAcls: { bypass: 'AzureServices', defaultAction: 'Allow' }
  }
}

resource vaultRead 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(vault.id, identity.id, keyVaultSecretsUserRole)
  scope: vault
  properties: {
    principalId: identity.properties.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: keyVaultSecretsUserRole
  }
}

resource vaultProvision 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(vault.id, deploymentPrincipalObjectId, keyVaultSecretsOfficerRole)
  scope: vault
  properties: {
    principalId: deploymentPrincipalObjectId
    principalType: 'ServicePrincipal'
    roleDefinitionId: keyVaultSecretsOfficerRole
  }
}

resource postgres 'Microsoft.DBforPostgreSQL/flexibleServers@2024-08-01' = {
  name: postgresName
  location: location
  sku: { name: 'Standard_B1ms', tier: 'Burstable' }
  properties: {
    version: '18'
    administratorLogin: 'm3admin'
    administratorLoginPassword: /* secure workflow parameter */ postgresAdministratorPassword
    availabilityZone: '1'
    backup: { backupRetentionDays: 7, geoRedundantBackup: 'Disabled' }
    highAvailability: { mode: 'Disabled' }
    network: { publicNetworkAccess: 'Enabled' }
    storage: { storageSizeGB: 32 }
  }
}

resource database 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2024-08-01' = {
  parent: postgres
  name: 'broker_gateway_m3'
  properties: { charset: 'UTF8', collation: 'en_US.utf8' }
}

resource allowAzure 'Microsoft.DBforPostgreSQL/flexibleServers/firewallRules@2024-08-01' = {
  parent: postgres
  name: 'AllowAzureServices'
  properties: { startIpAddress: '0.0.0.0', endIpAddress: '0.0.0.0' }
}

resource plan 'Microsoft.Web/serverfarms@2025-03-01' = {
  name: planName
  location: location
  kind: 'linux'
  sku: { name: 'B1', tier: 'Basic', capacity: 1 }
  properties: { reserved: true }
}

resource vendor 'Microsoft.Web/sites@2025-03-01' = {
  name: vendorName
  location: location
  kind: 'app,linux,container'
  properties: {
    serverFarmId: plan.id
    httpsOnly: true
    clientCertEnabled: true
    clientCertMode: 'Required'
    clientCertExclusionPaths: '/health/ready'
    siteConfig: {
      alwaysOn: true
      linuxFxVersion: 'DOCKER|${vendorImageReference}'
      healthCheckPath: '/health/ready'
      appSettings: [
        { name: 'WEBSITES_PORT', value: '8080' }
        { name: 'M3_VENDOR_API_KEY', value: vendorApiKey }
        { name: 'M3_VENDOR_CLIENT_THUMBPRINT', value: vendorClientThumbprint }
        { name: 'M3_VENDOR_CONTROL_TOKEN', value: vendorControlToken }
        { name: 'APPLICATIONINSIGHTS_CONNECTION_STRING', value: insights.properties.ConnectionString }
      ]
    }
  }
}

resource gateway 'Microsoft.Web/sites@2025-03-01' = {
  name: gatewayName
  location: location
  kind: 'app,linux,container'
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: { '${identity.id}': {} }
  }
  properties: {
    serverFarmId: plan.id
    httpsOnly: true
    keyVaultReferenceIdentity: identity.id
    clientCertEnabled: true
    clientCertMode: 'Required'
    clientCertExclusionPaths: '/health/live;/health/ready;/v1/enrollments/challenges;/v1/enrollments:activate'
    siteConfig: {
      alwaysOn: true
      linuxFxVersion: 'DOCKER|${gatewayImageReference}'
      healthCheckPath: '/health/live'
      acrUseManagedIdentityCreds: true
      acrUserManagedIdentityID: identity.properties.clientId
      appSettings: [
        { name: 'WEBSITES_PORT', value: '8080' }
        { name: 'ASPNETCORE_ENVIRONMENT', value: 'Production' }
        { name: 'ConnectionStrings__GatewayDatabase', value: '@Microsoft.KeyVault(SecretUri=${vault.properties.vaultUri}secrets/gateway-database-connection/)' }
        { name: 'Gateway__KeyVaultUri', value: vault.properties.vaultUri }
        { name: 'Gateway__ManagedIdentityClientId', value: identity.properties.clientId }
        { name: 'Gateway__ActivationHmacSecretReference', value: 'keyvault://${replace(replace(vault.properties.vaultUri, 'https://', ''), '/', '')}/activation-hmac' }
        { name: 'Gateway__TrustAzureAppServiceClientCertificateForwarding', value: 'true' }
        { name: 'Gateway__Operations__0__ConnectorId', value: 'm3-vendor' }
        { name: 'Gateway__Operations__0__OperationId', value: 'submit' }
        { name: 'Gateway__Operations__0__Version', value: '3.0.0-m3b' }
        { name: 'Gateway__Operations__0__Endpoint', value: 'https://${vendor.properties.defaultHostName}/vendor/orders' }
        { name: 'Gateway__Operations__0__Method', value: 'POST' }
        { name: 'Gateway__Operations__0__RequestContentType', value: 'application/json' }
        { name: 'Gateway__Operations__0__Authentication', value: 'ApiKeyAndMutualTls' }
        { name: 'Gateway__Operations__0__ApiKeySecretReference', value: 'keyvault://${replace(replace(vault.properties.vaultUri, 'https://', ''), '/', '')}/vendor-api-key' }
        { name: 'Gateway__Operations__0__ApiKeyHeaderName', value: 'X-Vendor-Api-Key' }
        { name: 'Gateway__Operations__0__ClientCertificateReference', value: 'keyvault://${replace(replace(vault.properties.vaultUri, 'https://', ''), '/', '')}/vendor-client-certificate' }
        { name: 'Gateway__Operations__0__MaximumRequestBytes', value: '1048576' }
        { name: 'Gateway__Operations__0__MaximumResponseBytes', value: '1048576' }
        { name: 'APPLICATIONINSIGHTS_CONNECTION_STRING', value: insights.properties.ConnectionString }
      ]
    }
  }
  dependsOn: [registryPull, vaultRead]
}

output registryName string = registry.name
output registryLoginServer string = registry.properties.loginServer
output vaultName string = vault.name
output vaultUri string = vault.properties.vaultUri
output gatewayName string = gateway.name
output gatewayUrl string = 'https://${gateway.properties.defaultHostName}/'
output gatewayManagedIdentityClientId string = identity.properties.clientId
output gatewayManagedIdentityPrincipalId string = identity.properties.principalId
output vendorName string = vendor.name
output vendorUrl string = 'https://${vendor.properties.defaultHostName}/'
output postgresServerName string = postgres.name
output postgresFqdn string = postgres.properties.fullyQualifiedDomainName
