<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>SecureIntegration.M3.SecurityDriver</AssemblyName>
    <RootNamespace>SecureIntegration.M3.SecurityDriver</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
