import { test, expect, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

const tenant = { id: '10000000-0000-0000-0000-000000000001', code: 'sample', displayName: 'Sample tenant', status: 'Active', createdAt: '2026-08-05T00:00:00Z' };
async function fixtures(page: Page, role = 'SecurityAdministrator') {
  await page.route('**/admin/auth/me', route => route.fulfill({ json: { id: '20000000-0000-0000-0000-000000000001', displayName: role, roles: [{ role, tenantId: null }] } }));
  await page.route('**/admin/auth/csrf', route => route.fulfill({ json: { token: 'synthetic-csrf' } }));
  await page.route('**/admin/api/v1/dashboard', route => route.fulfill({ json: { tenants: 1, applications: 1, database: 'healthy', provider: 'healthy', generatedAtUtc: '2026-08-05T00:00:00Z' } }));
  await page.route('**/admin/api/v1/tenants**', route => route.request().method() === 'POST' ? route.fulfill({ status: 201, json: tenant }) : route.fulfill({ json: { items: [tenant], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/applications**', route => route.fulfill({ json: { items: [{ id: '30000000-0000-0000-0000-000000000001', code: 'sample-app', displayName: 'Sample application', status: 'Active', minimumBrokerVersion: '3.0.0', createdAt: '2026-08-05T00:00:00Z' }], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/environments**', route => route.fulfill({ json: { items: [{ id: '50000000-0000-0000-0000-000000000001', code: 'local', displayName: 'Local', productionControls: false }], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/installations**', route => route.request().method() === 'POST' && !route.request().url().includes(':revoke') ? route.fulfill({ status: 201, json: { installationId: '40000000-0000-0000-0000-000000000002', activationCodeId: '70000000-0000-0000-0000-000000000001', activationCode: 'SYNTHETIC-ONE-TIME', expiresAt: '2026-08-05T01:00:00Z' } }) : route.request().url().includes(':revoke') ? route.fulfill({ json: { status: 'revoked' } }) : route.fulfill({ json: { items: [{ id: '40000000-0000-0000-0000-000000000001', tenantId: tenant.id, applicationId: '30000000-0000-0000-0000-000000000001', environmentId: '50000000-0000-0000-0000-000000000001', status: 'Active', brokerVersion: '3.0.0', createdAt: '2026-08-05T00:00:00Z' }], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/connectors', route => route.fulfill({ json: [{ connectorId: 'sample-secure-service', displayName: 'Sample secure service', versions: 2, publishedVersion: '1.0.0', publicationRevision: 2 }] }));
  await page.route('**/admin/api/v1/connectors:validate', route => route.fulfill({ json: { valid: true, checksumSha256: 'A'.repeat(64), errors: [] } }));
  await page.route('**/admin/api/v1/connectors:import', route => route.fulfill({ status: 201, json: { state: 'Draft' } }));
  await page.route('**/admin/api/v1/grants**', route => route.request().method() === 'POST' ? route.fulfill({ status: 201, json: { id: 'new-grant' } }) : route.fulfill({ json: { items: [{ id: 'g', installationId: 'i', tenantId: tenant.id, connectorId: 'sample-secure-service', operationId: 'submit', enabled: true, validFrom: '2026-08-05T00:00:00Z' }], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/audit**', route => route.fulfill({ json: { items: [{ id: 'a', occurredAt: '2026-08-05T00:00:00Z', action: 'connector.publish', targetType: 'connector', targetId: 'sample-secure-service', correlationId: '60000000-0000-0000-0000-000000000001', outcome: 'success', reasonCode: 'BGW-ADMIN-ACTION' }], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/role-assignments', route => route.fulfill({ json: { id: 'role-assignment' } }));
  await page.route('**/admin/api/v1/connectors/**', route => { const url = route.request().url(); if (url.endsWith('/versions')) return route.fulfill({ json: [{ connectorId: 'sample-secure-service', version: '2.0.0', schemaVersion: '1.0', state: 'Validated', checksumSha256: 'B'.repeat(64), rowVersion: 2, createdAt: '2026-08-05T00:10:00Z' }, { connectorId: 'sample-secure-service', version: '1.0.0', schemaVersion: '1.0', state: 'Superseded', checksumSha256: 'A'.repeat(64), rowVersion: 3, createdAt: '2026-08-05T00:00:00Z' }] }); if (url.endsWith('/definition')) return route.fulfill({ json: { schemaVersion: '1.0', version: url.includes('2.0.0') ? '2.0.0' : '1.0.0' } }); if (url.includes(':test')) return route.fulfill({ json: { status: 'valid', connectorId: 'sample-secure-service', operationId: 'submit', connectorVersion: '1.0.0' } }); if (url.endsWith('/approvals') && route.request().method() === 'GET') return route.fulfill({ json: [] }); return route.fulfill({ json: { connectorId: 'sample-secure-service', version: '2.0.0', state: 'Published', rowVersion: 3 } }); });
}

test.beforeEach(async ({ page }) => { await fixtures(page); await page.goto('./'); });
test('E2E-01 viewer navigates read-only dashboard', async ({ page }) => { await expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible(); });
test('E2E-02 editor opens connector draft editor', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await expect(page.getByLabel('Connector JSON')).toBeVisible(); });
test('E2E-03 JSON validation reports success', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await page.getByRole('button', { name: 'Validate' }).click(); await expect(page.getByText(/Definition is valid/)).toBeVisible(); });
test('E2E-04 editor requests approval', async ({ page }) => { await page.getByRole('link', { name: 'Approvals' }).click(); await expect(page.getByRole('button', { name: 'Request approval' })).toBeVisible(); });
test('E2E-05 self approval failure is mapped safely', async ({ page }) => { await page.getByRole('link', { name: 'Approvals' }).click(); await page.route('**/admin/api/v1/connectors/*/versions/*/approvals', route => route.fulfill({ status: 403, json: { code: 'BGW-ADMIN-FOUR-EYES', correlationId: 'c' } })); await page.getByLabel('Connectors').fill('sample-secure-service'); await page.getByLabel('Version').fill('1.0.0'); await page.getByRole('button', { name: 'Approve' }).click(); await expect(page.getByText(/not authorized/i)).toBeVisible(); });
test('E2E-06 distinct approver action is exposed', async ({ page }) => { await page.getByRole('link', { name: 'Approvals' }).click(); await page.getByLabel('Connectors').fill('sample-secure-service'); await page.getByLabel('Version').fill('1.0.0'); await expect(page.getByRole('button', { name: 'Approve' })).toBeEnabled(); });
test('E2E-07 approved version can be published with server revision', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await page.getByRole('button', { name: 'sample-secure-service' }).click(); await page.getByRole('button', { name: 'Publish' }).click(); await expect(page.getByText('Version timeline: sample-secure-service')).toBeVisible(); });
test('E2E-08 grant editor is tenant and installation scoped', async ({ page }) => { await page.getByRole('link', { name: 'Grants' }).click(); await page.getByLabel('Select a tenant').click(); await page.getByRole('option', { name: 'Sample tenant' }).click(); await page.getByLabel('Installation').click(); await page.getByRole('option', { name: '40000000-0000-0000-0000-000000000001' }).click(); await page.getByLabel('Connectors').fill('sample-secure-service'); await page.getByLabel('Operation').fill('submit'); await expect(page.getByRole('button', { name: 'Create' })).toBeEnabled(); });
test('E2E-09 controlled connector test is not an arbitrary proxy', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await page.getByRole('button', { name: 'sample-secure-service' }).click(); await page.getByLabel('Environment').click(); await page.getByRole('option', { name: 'Local' }).click(); await page.getByLabel('Operation').fill('submit'); await page.getByRole('button', { name: 'Run controlled test' }).click(); await expect(page.getByText(/sample-secure-service · submit/)).toBeVisible(); });
test('E2E-10 version history exposes rollback action', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await page.getByRole('button', { name: 'sample-secure-service' }).click(); await expect(page.getByRole('button', { name: 'Rollback' })).toBeVisible(); });
test('E2E-11 retire is an explicit authorized action', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await page.getByRole('button', { name: 'sample-secure-service' }).click(); await expect(page.getByRole('button', { name: 'Retire' }).first()).toBeVisible(); });
test('E2E-12 activation code is displayed once in a transient modal', async ({ page }) => { await page.getByRole('link', { name: 'Installations' }).click(); await page.getByLabel('Select a tenant').click(); await page.getByRole('option', { name: 'Sample tenant' }).click(); await page.getByLabel('Application').click(); await page.getByRole('option', { name: 'Sample application' }).click(); await page.getByLabel('Environment').click(); await page.getByRole('option', { name: 'Local' }).click(); await page.getByRole('button', { name: 'Create installation' }).click(); await expect(page.getByRole('textbox', { name: 'Activation code' })).toHaveValue('SYNTHETIC-ONE-TIME'); await page.getByRole('button', { name: 'Close' }).click(); await expect(page.getByText('SYNTHETIC-ONE-TIME')).toHaveCount(0); });
test('E2E-13 installation inventory exposes revocation', async ({ page }) => { await page.getByRole('link', { name: 'Installations' }).click(); await page.getByLabel('Select a tenant').click(); await page.getByRole('option', { name: 'Sample tenant' }).click(); await expect(page.getByRole('button', { name: 'Revoke' })).toBeVisible(); });
test('E2E-14 concurrency conflict includes correlation id', async ({ page }) => { await page.route('**/admin/api/v1/connectors/*/versions/*:publish', route => route.fulfill({ status: 409, json: { code: 'BGW-CONCURRENCY', correlationId: 'conflict-correlation' } })); await page.getByRole('link', { name: 'Connectors' }).click(); await page.getByRole('button', { name: 'sample-secure-service' }).click(); await page.getByRole('button', { name: 'Publish' }).click(); await expect(page.getByText(/conflict-correlation/)).toBeVisible(); });
test('E2E-15 binding form never retrieves a secret value', async ({ page }) => { await page.getByRole('link', { name: 'Bindings' }).click(); await expect(page.getByText(/never displayed/)).toBeVisible(); });
test('E2E-16 audit action is visible and redacted', async ({ page }) => { await page.getByRole('link', { name: 'Audit' }).click(); await page.getByLabel('Select a tenant').click(); await page.getByRole('option', { name: 'Sample tenant' }).click(); await expect(page.getByText('connector.publish')).toBeVisible(); });
test('E2E-17 provider-neutral health is green', async ({ page }) => { await page.getByRole('link', { name: 'Health' }).click(); await expect(page.getByText('healthy').first()).toBeVisible(); });
test('E2E-18 language changes to Italian', async ({ page }) => { await page.getByLabel('Language').click(); await page.getByRole('option', { name: 'IT' }).click(); await expect(page.getByRole('link', { name: 'Panoramica' })).toBeVisible(); });
test('E2E-19 theme choice persists locally', async ({ page }) => { await page.getByLabel('Theme').click(); await page.getByRole('option', { name: 'Dark' }).click(); await expect.poll(() => page.evaluate(() => localStorage.getItem('sip.theme'))).toBe('dark'); });
test('E2E-20 primary flow has no serious accessibility violations', async ({ page }) => { const results = await new AxeBuilder({ page }).analyze(); expect(results.violations.filter(value => ['critical', 'serious'].includes(value.impact ?? ''))).toEqual([]); });
test('E2E-21 approver can explicitly reject an exact version', async ({ page }) => { await page.getByRole('link', { name: 'Approvals' }).click(); await page.getByLabel('Connectors').fill('sample-secure-service'); await page.getByLabel('Version').fill('2.0.0'); await expect(page.getByRole('button', { name: 'Reject' })).toBeEnabled(); });
test('E2E-22 security administrator can assign provider-neutral roles', async ({ page }) => { await page.getByRole('link', { name: 'Access control' }).click(); await page.getByLabel('OIDC issuer').fill('https://issuer.example.invalid'); await page.getByLabel('OIDC subject').fill('reviewer'); await page.getByLabel('Name').fill('Reviewer'); await page.getByRole('button', { name: 'Assign role' }).click(); await expect(page.getByRole('status')).toHaveText('Saved.'); });
test('E2E-23 canonical version comparison never requests bindings', async ({ page }) => { const requested: string[] = []; page.on('request', request => requested.push(request.url())); await page.getByRole('link', { name: 'Connectors' }).click(); await page.getByRole('button', { name: 'sample-secure-service' }).click(); await page.getByLabel('Base version').click(); await page.getByRole('option', { name: '1.0.0' }).click(); await page.getByLabel('Target version').click(); await page.getByRole('option', { name: '2.0.0' }).click(); await expect(page.getByRole('combobox', { name: 'Target version' })).toHaveText('2.0.0'); await expect(page.getByText(/"version": "2.0.0"/)).toBeVisible(); expect(requested.some(value => value.includes('/bindings'))).toBe(false); });
test('E2E-24 viewer does not see privileged access or approval actions', async ({ page }) => { await page.unroute('**/admin/auth/me'); await page.route('**/admin/auth/me', route => route.fulfill({ json: { id: '20000000-0000-0000-0000-000000000002', displayName: 'Viewer', roles: [{ role: 'Viewer', tenantId: null }] } })); await page.reload(); await expect(page.getByRole('link', { name: 'Access control' })).toHaveCount(0); await page.getByRole('link', { name: 'Approvals' }).click(); await expect(page.getByRole('button', { name: 'Request approval' })).toHaveCount(0); await expect(page.getByRole('button', { name: 'Approve' })).toHaveCount(0); await expect(page.getByRole('button', { name: 'Reject' })).toHaveCount(0); });
