import { test, expect, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

const tenant = { id: '10000000-0000-0000-0000-000000000001', code: 'sample', displayName: 'Sample tenant', status: 'Active', createdAt: '2026-08-05T00:00:00Z', rowVersion: 1 };
async function fixtures(page: Page, role = 'SecurityAdministrator') {
  await page.route('**/admin/auth/me', route => route.fulfill({ json: { id: '20000000-0000-0000-0000-000000000001', displayName: role, roles: [{ role, tenantId: null }] } }));
  await page.route('**/admin/auth/csrf', route => route.fulfill({ json: { token: 'synthetic-csrf' } }));
  await page.route('**/admin/api/v1/dashboard', route => route.fulfill({ json: { tenants: 1, applications: 1, database: 'healthy', provider: 'healthy', generatedAtUtc: '2026-08-05T00:00:00Z' } }));
  await page.route('**/admin/api/v1/tenants**', route => route.request().method() === 'POST' ? route.fulfill({ status: 201, json: tenant }) : route.fulfill({ json: { items: [tenant], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/applications**', route => route.fulfill({ json: { items: [{ id: '30000000-0000-0000-0000-000000000001', code: 'sample-app', displayName: 'Sample application', status: 'Active', minimumBrokerVersion: '3.0.0', maximumBrokerVersion: null, createdAt: '2026-08-05T00:00:00Z', rowVersion: 1 }], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/environments**', route => route.fulfill({ json: { items: [{ id: '50000000-0000-0000-0000-000000000001', code: 'local', displayName: 'Local', productionControls: false }], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/installations**', route => route.request().method() === 'POST' && !route.request().url().includes(':revoke') ? route.fulfill({ status: 201, json: { installationId: '40000000-0000-0000-0000-000000000002', activationCodeId: '70000000-0000-0000-0000-000000000001', activationCode: 'SYNTHETIC-ONE-TIME', expiresAt: '2026-08-05T01:00:00Z' } }) : route.request().url().includes(':revoke') ? route.fulfill({ json: { status: 'revoked' } }) : route.fulfill({ json: { items: [{ id: '40000000-0000-0000-0000-000000000001', tenantId: tenant.id, applicationId: '30000000-0000-0000-0000-000000000001', environmentId: '50000000-0000-0000-0000-000000000001', status: 'Active', brokerVersion: '3.0.0', createdAt: '2026-08-05T00:00:00Z' }], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/connectors?*', route => route.fulfill({ json: { items: [{ connectorId: 'sample-secure-service', displayName: 'Sample secure service', versions: 2, publishedVersion: '1.0.0', publicationRevision: 2 }], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/connectors:validate', route => route.fulfill({ json: { valid: true, checksumSha256: 'A'.repeat(64), errors: [] } }));
  await page.route('**/admin/api/v1/connectors:import', route => route.fulfill({ status: 201, json: { state: 'Draft' } }));
  await page.route('**/admin/api/v1/grants**', route => route.request().method() === 'POST' ? route.fulfill({ status: 201, json: { id: 'new-grant' } }) : route.fulfill({ json: { items: [{ id: 'g', installationId: 'i', tenantId: tenant.id, connectorId: 'sample-secure-service', operationId: 'submit', enabled: true, validFrom: '2026-08-05T00:00:00Z' }], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/audit**', route => route.fulfill({ json: { items: [{ id: 'a', occurredAt: '2026-08-05T00:00:00Z', action: 'connector.publish', targetType: 'connector', targetId: 'sample-secure-service', correlationId: '60000000-0000-0000-0000-000000000001', outcome: 'success', reasonCode: 'BGW-ADMIN-ACTION' }], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/role-assignments**', route => route.request().method() === 'GET' ? route.fulfill({ json: { items: [], offset: 0, limit: 50, total: 0 } }) : route.fulfill({ json: { id: 'role-assignment' } }));
  await page.route('**/admin/api/v1/connectors/**', route => { const url = new URL(route.request().url()); if (url.pathname.endsWith('/schema')) return route.fulfill({ json: { type: 'object' } }); if (url.pathname.endsWith('/sample')) return route.fulfill({ json: { schemaVersion: '1.0', connectorId: 'sample-secure-service', version: '1.0.0' } }); if (url.pathname.endsWith('/versions')) return route.fulfill({ json: { items: [{ connectorId: 'sample-secure-service', version: '2.0.0', schemaVersion: '1.0', state: 'Validated', checksumSha256: 'B'.repeat(64), rowVersion: 2, createdAt: '2026-08-05T00:10:00Z' }, { connectorId: 'sample-secure-service', version: '1.0.0', schemaVersion: '1.0', state: 'Superseded', checksumSha256: 'A'.repeat(64), rowVersion: 3, createdAt: '2026-08-05T00:00:00Z' }], offset: 0, limit: 50, total: 2 } }); if (url.pathname.endsWith('/definition')) return route.fulfill({ json: { schemaVersion: '1.0', version: url.pathname.includes('2.0.0') ? '2.0.0' : '1.0.0' } }); if (url.pathname.endsWith('/bindings')) return route.request().method() === 'GET' ? route.fulfill({ json: { items: [{ id: 'binding', connectorId: 'sample-secure-service', connectorVersionId: 'version-id', environmentId: '50000000-0000-0000-0000-000000000001', endpoints: { endpoint: '[REDACTED]' }, secretReferences: { secret: '[REDACTED]' }, certificateReferences: { certificate: '[REDACTED]' }, endpointChecksumSha256: 'E'.repeat(64), secretChecksumSha256: 'F'.repeat(64), certificateChecksumSha256: '9'.repeat(64), revision: 4, checksumSha256: 'C'.repeat(64), state: 'Active', updatedAt: '2026-08-05T00:00:00Z', updatedBy: 'editor' }], offset: 0, limit: 50, total: 1 } }) : route.fulfill({ json: { revision: 5 } }); if (url.pathname.includes(':test')) return route.fulfill({ json: { status: 'valid', connectorId: 'sample-secure-service', operationId: 'submit', connectorVersion: '1.0.0' } }); return route.fulfill({ json: { connectorId: 'sample-secure-service', version: '2.0.0', state: 'Published', rowVersion: 3 } }); });
  await page.route('**/admin/api/v1/connectors/*/versions/*/approvals?*', route => route.fulfill({ json: { items: [{ id: 'approval', connectorVersionId: 'version-id', checksumSha256: 'B'.repeat(64), bindingDigestSha256: 'D'.repeat(64), requestedBy: '20000000-0000-0000-0000-000000000002', status: 'Requested', requestedAt: '2026-08-05T00:00:00Z' }], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/connectors/*/versions/*/approval-review', route => route.fulfill({ json: {
    artifact: { connector: { connectorId: 'sample-secure-service', version: '2.0.0', displayName: 'Sample secure service', schemaVersion: '1.0', canonicalDefinitionChecksumSha256: 'B'.repeat(64) }, operations: [{ operationId: 'submit', environment: '50000000-0000-0000-0000-000000000001', executionStrategy: 'gateway-server-side', protocol: 'HTTPS', endpoint: { logicalBindingId: 'sample-vendor-endpoint', revision: 4, scheme: 'https', hostname: 'vendor.example.test', port: 443, path: '/vendor/orders', allowedMethods: ['POST'], redirectPolicy: 'deny', tlsPolicy: 'validate-system-trust-and-hostname', endpointChecksumSha256: 'E'.repeat(64), destinationClassification: 'publicInternet' }, secretBindings: [{ logicalBindingId: 'sample-vendor-api-key', revision: 4, providerDisplayName: 'Synthetic vault', providerType: 'synthetic-vault', providerId: 'vault.m3.test', resourceLogicalId: 'vendor-api-key', resourceType: 'secret', environment: '50000000-0000-0000-0000-000000000001', connectorScope: 'sample-secure-service', operationScope: 'submit', secretBindingChecksumSha256: 'F'.repeat(64) }], certificateBindings: [{ logicalBindingId: 'sample-vendor-client-certificate', revision: 4, providerDisplayName: 'Synthetic vault', providerType: 'synthetic-vault', providerId: 'vault.m3.test', certificateLogicalId: 'vendor-client-certificate', publicFingerprintSha256: null, publicSubject: null, publicIssuer: null, expiresAt: null, environment: '50000000-0000-0000-0000-000000000001', connectorScope: 'sample-secure-service', operationScope: 'submit', certificateBindingChecksumSha256: '9'.repeat(64) }] }] },
    canonicalJson: '{"redacted":true}', digestSha256: 'D'.repeat(64), revisions: [{ bindingId: 'binding', environmentId: '50000000-0000-0000-0000-000000000001', revision: 4, checksumSha256: 'C'.repeat(64) }], diff: [{ change: 'changed', path: '/operations/0/endpoint/hostname', previousValue: '"old.example.test"', currentValue: '"vendor.example.test"' }], riskIndicators: [{ code: 'PUBLIC_INTERNET_DESTINATION', severity: 'high', path: '/operations' }]
  } }));
}

test.beforeEach(async ({ page }) => { await fixtures(page); await page.goto('./'); });
test('UI-MOCK-01 viewer navigates read-only dashboard', async ({ page }) => { await expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible(); });
test('UI-MOCK-02 editor opens connector draft editor', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await expect(page.getByLabel('Connector JSON')).toBeVisible(); });
test('UI-MOCK-03 JSON validation reports success', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await page.getByRole('button', { name: 'Validate' }).click(); await expect(page.getByText(/Definition is valid/)).toBeVisible(); });
test('UI-MOCK-04 editor requests approval', async ({ page }) => { await page.getByRole('link', { name: 'Approvals' }).click(); await expect(page.getByRole('button', { name: 'Request approval' })).toBeVisible(); });
test('UI-MOCK-05 self approval failure is mapped safely', async ({ page }) => { await page.getByRole('link', { name: 'Approvals' }).click(); await page.route('**/admin/api/v1/connectors/*/versions/*/approvals', route => route.fulfill({ status: 403, json: { code: 'BGW-ADMIN-FOUR-EYES', correlationId: 'c' } })); await page.getByLabel('Connectors').fill('sample-secure-service'); await page.getByLabel('Version').fill('1.0.0'); await page.getByRole('button', { name: 'Approve' }).click(); await expect(page.getByText(/not authorized/i)).toBeVisible(); });
test('UI-MOCK-06 distinct approver action is exposed', async ({ page }) => { await page.getByRole('link', { name: 'Approvals' }).click(); await page.getByLabel('Connectors').fill('sample-secure-service'); await page.getByLabel('Version').fill('1.0.0'); await expect(page.getByRole('button', { name: 'Approve' })).toBeEnabled(); });
test('UI-MOCK-07 approved version can be published with server revision', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await page.getByRole('button', { name: 'sample-secure-service' }).click(); await page.getByRole('button', { name: 'Publish' }).click(); await expect(page.getByText('Version timeline: sample-secure-service')).toBeVisible(); });
test('UI-MOCK-08 grant editor is tenant and installation scoped', async ({ page }) => { await page.getByRole('link', { name: 'Grants' }).click(); await page.getByLabel('Select a tenant').click(); await page.getByRole('option', { name: 'Sample tenant' }).click(); await page.getByLabel('Installation').click(); await page.getByRole('option', { name: '40000000-0000-0000-0000-000000000001' }).click(); await page.getByLabel('Connectors').fill('sample-secure-service'); await page.getByLabel('Operation').fill('submit'); await expect(page.getByRole('button', { name: 'Create' })).toBeEnabled(); });
test('UI-MOCK-09 controlled connector test is not an arbitrary proxy', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await page.getByRole('button', { name: 'sample-secure-service' }).click(); await page.getByLabel('Environment').click(); await page.getByRole('option', { name: 'Local' }).click(); await page.getByLabel('Operation').fill('submit'); await page.getByRole('button', { name: 'Run controlled test' }).click(); await expect(page.getByText(/sample-secure-service · submit/)).toBeVisible(); });
test('UI-MOCK-10 version history exposes rollback action', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await page.getByRole('button', { name: 'sample-secure-service' }).click(); await expect(page.getByRole('button', { name: 'Rollback' })).toBeVisible(); });
test('UI-MOCK-11 retire is an explicit authorized action', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await page.getByRole('button', { name: 'sample-secure-service' }).click(); await expect(page.getByRole('button', { name: 'Retire' }).first()).toBeVisible(); });
test('UI-MOCK-12 activation code is displayed once in a transient modal', async ({ page }) => { await page.getByRole('link', { name: 'Installations' }).click(); await page.getByLabel('Select a tenant').click(); await page.getByRole('option', { name: 'Sample tenant' }).click(); await page.getByLabel('Application').click(); await page.getByRole('option', { name: 'Sample application' }).click(); await page.getByLabel('Environment').click(); await page.getByRole('option', { name: 'Local' }).click(); await page.getByRole('button', { name: 'Create installation' }).click(); await expect(page.getByRole('textbox', { name: 'Activation code' })).toHaveValue('SYNTHETIC-ONE-TIME'); await page.getByRole('button', { name: 'Close' }).click(); await expect(page.getByText('SYNTHETIC-ONE-TIME')).toHaveCount(0); });
test('UI-MOCK-13 installation inventory exposes revocation', async ({ page }) => { await page.getByRole('link', { name: 'Installations' }).click(); await page.getByLabel('Select a tenant').click(); await page.getByRole('option', { name: 'Sample tenant' }).click(); await expect(page.getByRole('button', { name: 'Revoke' })).toBeVisible(); });
test('UI-MOCK-14 concurrency conflict includes correlation id', async ({ page }) => { await page.route('**/admin/api/v1/connectors/*/versions/*:publish', route => route.fulfill({ status: 409, json: { code: 'BGW-CONCURRENCY', correlationId: 'conflict-correlation' } })); await page.getByRole('link', { name: 'Connectors' }).click(); await page.getByRole('button', { name: 'sample-secure-service' }).click(); await page.getByRole('button', { name: 'Publish' }).click(); await expect(page.getByText(/conflict-correlation/)).toBeVisible(); });
test('UI-MOCK-15 binding form never retrieves a secret value', async ({ page }) => { await page.getByRole('link', { name: 'Bindings' }).click(); await expect(page.getByText(/never (shown|displayed)/).first()).toBeVisible(); });
test('UI-MOCK-16 audit action is visible and redacted', async ({ page }) => { await page.getByRole('link', { name: 'Audit' }).click(); await page.getByLabel('Select a tenant').click(); await page.getByRole('option', { name: 'Sample tenant' }).click(); await expect(page.getByText('connector.publish')).toBeVisible(); });
test('UI-MOCK-17 provider-neutral health is green', async ({ page }) => { await page.getByRole('link', { name: 'Health' }).click(); await expect(page.getByText('healthy').first()).toBeVisible(); });
test('UI-MOCK-18 language changes to Italian', async ({ page }) => { await page.getByLabel('Language').click(); await page.getByRole('option', { name: 'IT' }).click(); await expect(page.getByRole('link', { name: 'Panoramica' })).toBeVisible(); });
test('UI-MOCK-19 theme choice persists locally', async ({ page }) => { await page.getByLabel('Theme').click(); await page.getByRole('option', { name: 'Dark' }).click(); await expect.poll(() => page.evaluate(() => localStorage.getItem('sip.theme'))).toBe('dark'); });
test('UI-MOCK-20 opened forms have no serious accessibility violations', async ({ page }) => { for (const name of ['Tenants', 'Applications', 'Bindings', 'Connectors', 'Access control']) { await page.getByRole('link', { name }).click(); if (name === 'Tenants') await page.getByRole('button', { name: 'Add tenant' }).click(); if (name === 'Applications') await page.getByRole('button', { name: 'Add application' }).click(); const results = await new AxeBuilder({ page }).analyze(); expect(results.violations.filter(value => ['critical', 'serious'].includes(value.impact ?? '')), name).toEqual([]); if (name === 'Tenants' || name === 'Applications') await page.getByRole('button', { name: 'Cancel' }).click(); } });
test('UI-MOCK-21 approver can explicitly reject an exact version', async ({ page }) => { await page.getByRole('link', { name: 'Approvals' }).click(); await page.getByLabel('Connectors').fill('sample-secure-service'); await page.getByLabel('Version').fill('2.0.0'); await expect(page.getByRole('button', { name: 'Reject' })).toBeEnabled(); });
test('UI-MOCK-22 security administrator can assign provider-neutral roles', async ({ page }) => { await page.getByRole('link', { name: 'Access control' }).click(); await page.getByLabel('OIDC issuer').fill('https://issuer.example.invalid'); await page.getByLabel('OIDC subject').fill('reviewer'); await page.getByLabel('Name').fill('Reviewer'); await page.getByRole('button', { name: 'Assign role' }).click(); await expect(page.getByRole('status')).toHaveText('Saved.'); });
test('UI-MOCK-23 canonical version comparison shows a non-color path diff and never requests bindings', async ({ page }) => { const requested: string[] = []; page.on('request', request => requested.push(request.url())); await page.getByRole('link', { name: 'Connectors' }).click(); await page.getByRole('button', { name: 'sample-secure-service' }).click(); await page.getByLabel('Base version').click(); await page.getByRole('option', { name: '1.0.0' }).click(); await page.getByLabel('Target version').click(); await page.getByRole('option', { name: '2.0.0' }).click(); const diff = page.getByRole('table', { name: 'Canonical JSON path differences' }); await expect(diff).toContainText('changed'); await expect(diff).toContainText('/version'); expect(requested.some(value => value.includes('/bindings'))).toBe(false); });
test('UI-MOCK-24 viewer does not see privileged access or approval actions', async ({ page }) => { await page.unroute('**/admin/auth/me'); await page.route('**/admin/auth/me', route => route.fulfill({ json: { id: '20000000-0000-0000-0000-000000000002', displayName: 'Viewer', roles: [{ role: 'Viewer', tenantId: null }] } })); await page.reload(); await expect(page.getByRole('link', { name: 'Access control' })).toHaveCount(0); await page.getByRole('link', { name: 'Approvals' }).click(); await expect(page.getByRole('button', { name: 'Request approval' })).toHaveCount(0); await expect(page.getByRole('button', { name: 'Approve' })).toHaveCount(0); await expect(page.getByRole('button', { name: 'Reject' })).toHaveCount(0); });
test('UI-MOCK-25 CodeMirror exposes accessibility attributes on the contenteditable element', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await expect(page.locator('[contenteditable="true"][aria-label="Connector JSON"][aria-describedby*="connector-json-help"]')).toBeVisible(); });
test('UI-MOCK-26 dirty binding form can stay or explicitly discard through router navigation', async ({ page }) => { await page.getByRole('link', { name: 'Bindings' }).click(); await page.getByLabel('Connectors').fill('sample-secure-service'); await page.getByRole('link', { name: 'Grants' }).click(); await expect(page.getByRole('dialog', { name: 'Unsaved changes' })).toBeVisible(); await page.getByRole('button', { name: 'Stay' }).click(); await expect(page.getByRole('heading', { name: 'Bindings' })).toBeVisible(); await page.getByRole('link', { name: 'Grants' }).click(); await page.getByRole('button', { name: 'Discard' }).click(); await expect(page.getByRole('heading', { name: 'Grants' })).toBeVisible(); });
test('UI-MOCK-27 binding editor atomically sends multiple maps with If-Match', async ({ page }) => { let observed: { body?: string; ifMatch?: string | null } = {}; await page.route('**/admin/api/v1/connectors/sample-secure-service/bindings', async route => { if (route.request().method() === 'PUT') { observed = { body: route.request().postData() ?? undefined, ifMatch: route.request().headers()['if-match'] }; await route.fulfill({ json: { revision: 5 } }); } else await route.fallback(); }); await page.getByRole('link', { name: 'Bindings' }).click(); await page.getByLabel('Connectors').fill('sample-secure-service'); await page.getByLabel('Version').fill('1.0.0'); await page.getByLabel('Environment').fill('50000000-0000-0000-0000-000000000001'); await expect(page.getByText('CCCCCCCCCCCC')).toBeVisible(); await page.getByLabel('Endpoint bindings (JSON object)').fill('{"primary":"https://vendor.example","backup":"https://backup.example"}'); await page.getByLabel('Secret references (JSON object)').fill('{"apiKey":"synthetic://api-key"}'); await page.getByLabel('Certificate references (JSON object)').fill('{"mtls":"synthetic://client-cert"}'); await page.getByRole('button', { name: 'Save' }).click(); await expect(page.getByRole('status')).toHaveText('Saved.'); expect(observed.ifMatch).toBe('"4"'); expect(JSON.parse(observed.body ?? '{}').endpoints).toEqual({ backup: 'https://backup.example', primary: 'https://vendor.example' }); });
test('UI-MOCK-28 operational dialogs diffs filters and pagination have no serious accessibility violations', async ({ page }) => {
  test.setTimeout(90_000);
  const verify = async (surface: string) => { await page.waitForTimeout(500); const results = await new AxeBuilder({ page }).analyze(); expect(results.violations.filter(value => ['critical', 'serious'].includes(value.impact ?? '')), surface).toEqual([]); };
  await page.getByRole('link', { name: 'Approvals' }).click(); await verify('approval workflow');
  await page.getByRole('link', { name: 'Installations' }).click(); await page.getByLabel('Select a tenant').click(); await page.getByRole('option', { name: 'Sample tenant' }).click(); await page.getByLabel('Application').click(); await page.getByRole('option', { name: 'Sample application' }).click(); await page.getByLabel('Environment').click(); await page.getByRole('option', { name: 'Local' }).click(); await page.getByRole('button', { name: 'Create installation' }).click(); await verify('activation code dialog'); await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('link', { name: 'Audit' }).click(); await page.getByLabel('Select a tenant').click(); await page.getByRole('option', { name: 'Sample tenant' }).click(); await verify('audit filters');
  await page.getByRole('link', { name: 'Connectors' }).click(); await page.getByRole('button', { name: 'sample-secure-service' }).click(); await page.getByLabel('Base version').click(); await page.getByRole('option', { name: '1.0.0' }).click(); await page.getByLabel('Target version').click(); await page.getByRole('option', { name: '2.0.0' }).click(); await verify('canonical diff');
  await page.unroute('**/admin/api/v1/tenants**'); await page.route('**/admin/api/v1/tenants**', route => route.fulfill({ json: { items: [tenant], offset: 0, limit: 50, total: 101 } })); await page.getByRole('link', { name: 'Tenants' }).click(); await expect(page.getByRole('button', { name: 'Next' })).toBeEnabled(); await verify('pagination');
});
test('UI-MOCK-29 approval submits the exact semantic digest and never exposes a credential value', async ({ page }) => { let body = ''; await page.route('**/admin/api/v1/connectors/*/versions/*/approvals', async route => { body = route.request().postData() ?? ''; await route.fulfill({ json: { status: 'Approved' } }); }); await page.getByRole('link', { name: 'Approvals' }).click(); await page.getByLabel('Connectors').fill('sample-secure-service'); await page.getByLabel('Version').fill('2.0.0'); await expect(page.getByTestId('approval-publication-digest')).toHaveText('D'.repeat(64)); await expect(page.getByTestId('approval-semantic-sentence')).toContainText('https://vendor.example.test:443/vendor/orders'); await expect(page.getByRole('table', { name: 'Canonical approval diff' })).toContainText('/operations/0/endpoint/hostname'); await page.getByRole('button', { name: 'Approve' }).click(); expect(JSON.parse(body)).toMatchObject({ approvalRequestId: 'approval', expectedDigestSha256: 'D'.repeat(64) }); await expect(page.getByText(/SYNTHETIC-CANARY-SECRET/)).toHaveCount(0); });
test('UI-MOCK-30 browser Back keeps dirty edits until explicit confirmation', async ({ page }) => { await page.getByRole('link', { name: 'Bindings' }).click(); await page.getByLabel('Connectors').fill('sample-secure-service'); await page.goBack(); await expect(page.getByRole('dialog', { name: 'Unsaved changes' })).toBeVisible(); await page.getByRole('button', { name: 'Stay' }).click(); await expect(page.getByLabel('Connectors')).toHaveValue('sample-secure-service'); });
test('UI-MOCK-31 paged selector reaches records 51 and 101 with keyboard-visible controls', async ({ page }) => { await page.unroute('**/admin/api/v1/tenants**'); await page.route('**/admin/api/v1/tenants**', route => { const offset = Number(new URL(route.request().url()).searchParams.get('offset') ?? 0); const number = offset + 1; return route.fulfill({ json: { items: [{ ...tenant, id: `10000000-0000-0000-0000-${String(number).padStart(12, '0')}`, displayName: `Tenant ${number}` }], offset, limit: 50, total: 101 } }); }); await page.getByRole('link', { name: 'Installations' }).click(); const pager = page.getByTestId('tenant-installations-pagination'); await pager.getByRole('button', { name: 'Next' }).focus(); await page.keyboard.press('Enter'); await page.getByRole('combobox', { name: 'Select a tenant' }).click(); await expect(page.getByRole('option', { name: 'Tenant 51' })).toBeVisible(); await page.keyboard.press('Escape'); await pager.getByRole('button', { name: 'Next' }).focus(); await page.keyboard.press('Enter'); await page.getByRole('combobox', { name: 'Select a tenant' }).click(); await page.getByRole('option', { name: 'Tenant 101' }).click(); await expect(page.getByRole('combobox', { name: 'Select a tenant' })).toHaveText(/Tenant 101/); });
test('UI-MOCK-32 remediation strings are localized in Italian without key fallback', async ({ page }) => { await page.getByLabel('Language').click(); await page.getByRole('option', { name: 'IT' }).click(); await page.getByRole('link', { name: 'Binding' }).click(); await expect(page.getByLabel('Binding endpoint (oggetto JSON)')).toBeVisible(); await expect(page.getByText(/Invia il set completo/)).toBeVisible(); });
test('UI-MOCK-33 Italian mode covers the administrative approval surfaces without English fallback', async ({ page }) => { await page.getByLabel('Language').click(); await page.getByRole('option', { name: 'IT' }).click(); for (const [link, heading] of [['Tenant', 'Tenant'], ['Applicazioni', 'Applicazioni'], ['Connettori', 'Connettori'], ['Autorizzazioni', 'Autorizzazioni'], ['Audit', 'Audit'], ['Stato', 'Stato']] as const) { await page.getByRole('link', { name: link, exact: true }).click(); await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible(); } await page.getByRole('link', { name: 'Approvazioni' }).click(); await page.getByLabel('Connettori').fill('sample-secure-service'); await page.getByLabel('Versione').fill('2.0.0'); await expect(page.getByText('Destinazione Internet pubblica').first()).toBeVisible(); await expect(page.getByText(/Questa operazione utilizzerà la credenziale logica/)).toBeVisible(); });
test('UI-MOCK-34 stale Tenant ETag opens a localized compare-and-reload conflict instead of overwriting', async ({ page }) => { await page.route(`**/admin/api/v1/tenants/${tenant.id}`, route => route.request().method() === 'PUT' ? route.fulfill({ status: 409, json: { code: 'BGW-CONCURRENCY-CONFLICT', correlationId: 'tenant-conflict' } }) : route.fulfill({ json: { ...tenant, displayName: 'Current server tenant', rowVersion: 2 } })); await page.getByRole('link', { name: 'Tenants' }).click(); await page.getByRole('button', { name: 'Edit' }).click(); await page.getByLabel('Name').fill('My stale edit'); await page.getByRole('button', { name: 'Save' }).click(); await expect(page.getByText(/Another administrator changed this resource/)).toBeVisible(); await expect(page.getByText(/Current server tenant/)).toBeVisible(); await page.getByRole('button', { name: 'Reload current data' }).click(); await expect(page.getByLabel('Name')).toHaveValue('Current server tenant'); });
test('UI-MOCK-35 stale Application ETag opens a compare-and-reload conflict instead of overwriting', async ({ page }) => { const application = { id: '30000000-0000-0000-0000-000000000001', code: 'sample-app', displayName: 'Sample application', status: 'Active', minimumBrokerVersion: '3.0.0', maximumBrokerVersion: null, createdAt: '2026-08-05T00:00:00Z', rowVersion: 1 }; await page.route(`**/admin/api/v1/applications/${application.id}`, route => route.request().method() === 'PUT' ? route.fulfill({ status: 409, json: { code: 'BGW-CONCURRENCY-CONFLICT', correlationId: 'application-conflict' } }) : route.fulfill({ json: { ...application, displayName: 'Current server application', rowVersion: 2 } })); await page.getByRole('link', { name: 'Applications' }).click(); await page.getByRole('button', { name: 'Edit' }).click(); await page.getByLabel('Name').fill('My stale application edit'); await page.getByRole('button', { name: 'Save' }).click(); await expect(page.getByText(/Another administrator changed this resource/)).toBeVisible(); await expect(page.getByText(/Current server application/)).toBeVisible(); await page.getByRole('button', { name: 'Reload current data' }).click(); await expect(page.getByLabel('Name')).toHaveValue('Current server application'); });
