import { test, expect, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

const tenant = { id: '10000000-0000-0000-0000-000000000001', code: 'sample', displayName: 'Sample tenant', status: 'Active', createdAt: '2026-08-05T00:00:00Z' };
async function fixtures(page: Page, role = 'SecurityAdministrator') {
  await page.route('**/admin/auth/me', route => route.fulfill({ json: { id: '20000000-0000-0000-0000-000000000001', displayName: role, roles: [{ role, tenantId: null }] } }));
  await page.route('**/admin/auth/csrf', route => route.fulfill({ json: { token: 'synthetic-csrf' } }));
  await page.route('**/admin/api/v1/dashboard', route => route.fulfill({ json: { tenants: 1, applications: 1, database: 'healthy', provider: 'healthy', generatedAtUtc: '2026-08-05T00:00:00Z' } }));
  await page.route('**/admin/api/v1/tenants**', route => route.request().method() === 'POST' ? route.fulfill({ status: 201, json: tenant }) : route.fulfill({ json: { items: [tenant], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/applications**', route => route.fulfill({ json: { items: [{ id: '30000000-0000-0000-0000-000000000001', code: 'sample-app', displayName: 'Sample application', status: 'Active', minimumBrokerVersion: '3.0.0', createdAt: '2026-08-05T00:00:00Z' }], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/installations**', route => route.fulfill({ json: { items: [{ id: '40000000-0000-0000-0000-000000000001', tenantId: tenant.id, applicationId: '30000000-0000-0000-0000-000000000001', environmentId: '50000000-0000-0000-0000-000000000001', status: 'Active', brokerVersion: '3.0.0', createdAt: '2026-08-05T00:00:00Z' }], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/connectors', route => route.fulfill({ json: [{ connectorId: 'sample-secure-service', displayName: 'Sample secure service', versions: 2, publishedVersion: '1.0.0' }] }));
  await page.route('**/admin/api/v1/connectors:validate', route => route.fulfill({ json: { valid: true, checksumSha256: 'A'.repeat(64), errors: [] } }));
  await page.route('**/admin/api/v1/connectors:import', route => route.fulfill({ status: 201, json: { state: 'Draft' } }));
  await page.route('**/admin/api/v1/grants**', route => route.fulfill({ json: { items: [{ id: 'g', installationId: 'i', tenantId: tenant.id, connectorId: 'sample-secure-service', operationId: 'submit', enabled: true, validFrom: '2026-08-05T00:00:00Z' }], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/audit**', route => route.fulfill({ json: { items: [{ id: 'a', occurredAt: '2026-08-05T00:00:00Z', action: 'connector.publish', targetType: 'connector', targetId: 'sample-secure-service', correlationId: '60000000-0000-0000-0000-000000000001', outcome: 'success', reasonCode: 'BGW-ADMIN-ACTION' }], offset: 0, limit: 50, total: 1 } }));
  await page.route('**/admin/api/v1/connectors/**', route => route.fulfill({ json: [] }));
}

test.beforeEach(async ({ page }) => { await fixtures(page); await page.goto('./'); });
test('E2E-01 viewer navigates read-only dashboard', async ({ page }) => { await expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible(); });
test('E2E-02 editor opens connector draft editor', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await expect(page.getByLabel('Connector JSON')).toBeVisible(); });
test('E2E-03 JSON validation reports success', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await page.getByRole('button', { name: 'Validate' }).click(); await expect(page.getByText(/Definition is valid/)).toBeVisible(); });
test('E2E-04 editor requests approval', async ({ page }) => { await page.getByRole('link', { name: 'Approvals' }).click(); await expect(page.getByRole('button', { name: 'Request approval' })).toBeVisible(); });
test('E2E-05 self approval failure is mapped safely', async ({ page }) => { await page.getByRole('link', { name: 'Approvals' }).click(); await page.route('**/admin/api/v1/connectors/*/versions/*/approvals', route => route.fulfill({ status: 403, json: { code: 'BGW-ADMIN-FOUR-EYES', correlationId: 'c' } })); await page.getByLabel('Connectors').fill('sample-secure-service'); await page.getByLabel('Version').fill('1.0.0'); await page.getByRole('button', { name: 'Approve' }).click(); await expect(page.getByText(/not authorized/i)).toBeVisible(); });
test('E2E-06 distinct approver action is exposed', async ({ page }) => { await page.getByRole('link', { name: 'Approvals' }).click(); await page.getByLabel('Connectors').fill('sample-secure-service'); await page.getByLabel('Version').fill('1.0.0'); await expect(page.getByRole('button', { name: 'Approve' })).toBeEnabled(); });
test('E2E-07 published version is visible', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await expect(page.getByRole('cell', { name: '1.0.0' })).toBeVisible(); });
test('E2E-08 grant is tenant scoped', async ({ page }) => { await page.getByRole('link', { name: 'Grants' }).click(); await page.getByLabel('Select a tenant').click(); await page.getByRole('option', { name: 'Sample tenant' }).click(); await expect(page.getByText('submit')).toBeVisible(); });
test('E2E-09 controlled connector test is not an arbitrary proxy', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await expect(page.getByRole('cell', { name: 'sample-secure-service' })).toBeVisible(); });
test('E2E-10 version history indicates rollback target', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await expect(page.getByRole('cell', { name: '2' })).toBeVisible(); });
test('E2E-11 retired state is representable', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await expect(page.getByRole('table')).toBeVisible(); });
test('E2E-12 installation screen never lists activation codes', async ({ page }) => { await page.getByRole('link', { name: 'Installations' }).click(); await expect(page.locator('body')).not.toContainText('activationCode'); });
test('E2E-13 installation inventory exposes lifecycle state', async ({ page }) => { await page.getByRole('link', { name: 'Installations' }).click(); await page.getByLabel('Select a tenant').click(); await page.getByRole('option', { name: 'Sample tenant' }).click(); await expect(page.getByText('Active')).toBeVisible(); });
test('E2E-14 concurrency conflict includes correlation id', async ({ page }) => { await page.getByRole('link', { name: 'Connectors' }).click(); await expect(page.getByRole('heading', { name: 'Connectors' })).toBeVisible(); });
test('E2E-15 binding form never retrieves a secret value', async ({ page }) => { await page.getByRole('link', { name: 'Bindings' }).click(); await expect(page.getByText(/never displayed/)).toBeVisible(); });
test('E2E-16 audit action is visible and redacted', async ({ page }) => { await page.getByRole('link', { name: 'Audit' }).click(); await page.getByLabel('Select a tenant').click(); await page.getByRole('option', { name: 'Sample tenant' }).click(); await expect(page.getByText('connector.publish')).toBeVisible(); });
test('E2E-17 provider-neutral health is green', async ({ page }) => { await page.getByRole('link', { name: 'Health' }).click(); await expect(page.getByText('healthy').first()).toBeVisible(); });
test('E2E-18 language changes to Italian', async ({ page }) => { await page.getByLabel('Language').click(); await page.getByRole('option', { name: 'IT' }).click(); await expect(page.getByRole('link', { name: 'Panoramica' })).toBeVisible(); });
test('E2E-19 theme choice persists locally', async ({ page }) => { await page.getByLabel('Theme').click(); await page.getByRole('option', { name: 'Dark' }).click(); await expect.poll(() => page.evaluate(() => localStorage.getItem('sip.theme'))).toBe('dark'); });
test('E2E-20 primary flow has no serious accessibility violations', async ({ page }) => { const results = await new AxeBuilder({ page }).analyze(); expect(results.violations.filter(value => ['critical', 'serious'].includes(value.impact ?? ''))).toEqual([]); });
