<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>SecureIntegration.Broker.Core</AssemblyName>
    <RootNamespace>SecureIntegration.Broker.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Shared/SecureIntegration.Contracts/SecureIntegration.Contracts.csproj" />
  </ItemGroup>
</Project>

