import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const en = { translation: {
  product: 'Secure Integration Platform', dashboard: 'Dashboard', resources: 'Resources', integration: 'Integration', operations: 'Operations',
  tenants: 'Tenants', applications: 'Applications', installations: 'Installations', connectors: 'Connectors', bindings: 'Bindings', grants: 'Grants', approvals: 'Approvals', audit: 'Audit', health: 'Health',
  language: 'Language', theme: 'Theme', logout: 'Sign out', loginTitle: 'Administrative access', loginHelp: 'Use your configured identity provider. The synthetic users below exist only in local Development.', oidcLogin: 'Continue with identity provider',
  viewer: 'Viewer', editor: 'Editor', approver: 'Approver', operator: 'Operator', securityAdmin: 'Security administrator',
  status: 'Status', code: 'Code', name: 'Name', created: 'Created', action: 'Action', version: 'Version', total: 'Total', database: 'PostgreSQL', provider: 'Secret provider', lastUpdated: 'Last updated',
  loading: 'Loading…', empty: 'No records found.', retry: 'Retry', unavailable: 'The service is unavailable.', forbidden: 'You are not authorized for this action.', conflict: 'The resource changed. Reload before trying again.', unexpected: 'The request failed.', correlation: 'Correlation ID',
  create: 'Create', save: 'Save', cancel: 'Cancel', addTenant: 'Add tenant', addApplication: 'Add application', minimumBrokerVersion: 'Minimum Broker version', selectTenant: 'Select a tenant', id: 'Identifier', application: 'Application', environment: 'Environment', brokerVersion: 'Broker version', lastSeen: 'Last seen',
  connectorJson: 'Connector JSON', validate: 'Validate', importDraft: 'Import draft', checksum: 'Canonical checksum', validationPassed: 'Definition is valid.', validationFailed: 'Definition is not valid.', requestApproval: 'Request approval', approve: 'Approve', published: 'Published', operation: 'Operation', installation: 'Installation', validFrom: 'Valid from', outcome: 'Outcome', reason: 'Reason', target: 'Target',
  healthDescription: 'Provider-neutral readiness from the Gateway.', bindingsHelp: 'Map logical connector bindings to server-owned endpoints and provider references. Values are never returned after save.', endpointBinding: 'Endpoint binding', endpoint: 'HTTPS endpoint', secretBinding: 'Secret binding', secretReference: 'Provider reference', secretNeverShown: 'The value is stored server-side and is never displayed.', saved: 'Saved.', utc: 'UTC', themeLight: 'Light', themeDark: 'Dark', themeSystem: 'System', menu: 'Open navigation', close: 'Close', skip: 'Skip to content'
} };
const it = { translation: {
  ...en.translation, dashboard: 'Panoramica', resources: 'Risorse', integration: 'Integrazione', operations: 'Operazioni', tenants: 'Tenant', applications: 'Applicazioni', installations: 'Installazioni', connectors: 'Connettori', bindings: 'Binding', grants: 'Autorizzazioni', approvals: 'Approvazioni', audit: 'Audit', health: 'Stato', language: 'Lingua', theme: 'Tema', logout: 'Esci', loginTitle: 'Accesso amministrativo', loginHelp: 'Usa il provider di identità configurato. Gli utenti sintetici seguenti esistono soltanto in Development locale.', oidcLogin: 'Continua con il provider di identità', status: 'Stato', code: 'Codice', name: 'Nome', created: 'Creato', action: 'Azione', total: 'Totale', lastUpdated: 'Ultimo aggiornamento', loading: 'Caricamento…', empty: 'Nessun record presente.', retry: 'Riprova', unavailable: 'Il servizio non è disponibile.', forbidden: 'Non sei autorizzato per questa azione.', conflict: 'La risorsa è cambiata. Ricarica prima di riprovare.', unexpected: 'La richiesta non è riuscita.', correlation: 'ID correlazione', create: 'Crea', save: 'Salva', cancel: 'Annulla', addTenant: 'Aggiungi tenant', addApplication: 'Aggiungi applicazione', minimumBrokerVersion: 'Versione minima Broker', selectTenant: 'Seleziona un tenant', id: 'Identificatore', application: 'Applicazione', environment: 'Ambiente', brokerVersion: 'Versione Broker', lastSeen: 'Ultimo contatto', connectorJson: 'JSON connettore', validate: 'Valida', importDraft: 'Importa bozza', checksum: 'Checksum canonico', validationPassed: 'La definizione è valida.', validationFailed: 'La definizione non è valida.', requestApproval: 'Richiedi approvazione', approve: 'Approva', operation: 'Operazione', installation: 'Installazione', validFrom: 'Valido da', outcome: 'Esito', reason: 'Motivo', target: 'Destinazione', healthDescription: 'Readiness provider-neutral del Gateway.', bindingsHelp: 'Associa i binding logici a endpoint e riferimenti provider gestiti dal server. I valori non vengono mai restituiti dopo il salvataggio.', endpointBinding: 'Binding endpoint', endpoint: 'Endpoint HTTPS', secretBinding: 'Binding segreto', secretReference: 'Riferimento provider', secretNeverShown: 'Il valore resta lato server e non viene mai mostrato.', saved: 'Salvato.', themeLight: 'Chiaro', themeDark: 'Scuro', themeSystem: 'Sistema', menu: 'Apri navigazione', close: 'Chiudi', skip: 'Vai al contenuto'
} };

const stored = localStorage.getItem('sip.language');
void i18n.use(initReactI18next).init({ resources: { en, it }, lng: stored === 'it' ? 'it' : 'en', fallbackLng: 'en', interpolation: { escapeValue: false } });
export default i18n;
