import { useState } from 'react';
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, Stack, TextField } from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { useTranslation } from 'react-i18next';
import { adminApi, type Application } from '../../api/client';
import { hasRole, useSession } from '../../auth/SessionContext';
import { DataTable } from '../../components/DataTable'; import { ErrorState, LoadingState } from '../../components/AsyncState'; import { PageTitle } from '../../components/PageTitle';
import { PaginationControls } from '../../components/PaginationControls';
import { useFormDirty } from '../../navigation/DirtyStateContext';

export function ApplicationsPage() {
  const { t } = useTranslation(); const session = useSession(); const cache = useQueryClient(); const [open, setOpen] = useState(false); const [offset, setOffset] = useState(0); const form = useForm<{ code: string; displayName: string; minimumBrokerVersion: string }>({ defaultValues: { minimumBrokerVersion: '3.0.0' } });
  useFormDirty(open && form.formState.isDirty);
  const query = useQuery({ queryKey: ['applications', offset], queryFn: () => adminApi.applications(offset) }); const create = useMutation({ mutationFn: adminApi.createApplication, onSuccess: async () => { setOpen(false); form.reset(); await cache.invalidateQueries({ queryKey: ['applications'] }); } });
  if (query.isPending) return <LoadingState />; if (query.error) return <ErrorState error={query.error} retry={() => void query.refetch()} />;
  const columns = [{ key: 'code', label: t('code'), render: (row: Application) => row.code }, { key: 'name', label: t('name'), render: (row: Application) => row.displayName }, { key: 'version', label: t('minimumBrokerVersion'), render: (row: Application) => row.minimumBrokerVersion }, { key: 'status', label: t('status'), render: (row: Application) => row.status }];
  return <><PageTitle title={t('applications')} action={hasRole(session, 'SecurityAdministrator') ? <Button variant="contained" onClick={() => setOpen(true)}>{t('addApplication')}</Button> : undefined} /><DataTable rows={query.data.items ?? []} columns={columns} label={t('applications')} /><PaginationControls page={query.data} onOffset={setOffset} /><Dialog open={open} onClose={() => setOpen(false)}><form onSubmit={form.handleSubmit(value => create.mutate(value))} noValidate><DialogTitle>{t('addApplication')}</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><TextField label={t('code')} {...form.register('code', { required: true })} error={Boolean(form.formState.errors.code)} helperText={form.formState.errors.code ? 'Application code is required.' : 'Stable application code.'} /><TextField label={t('name')} {...form.register('displayName', { required: true })} error={Boolean(form.formState.errors.displayName)} helperText={form.formState.errors.displayName ? 'Display name is required.' : 'Human-readable application name.'} /><TextField label={t('minimumBrokerVersion')} {...form.register('minimumBrokerVersion', { required: true, pattern: /^\d+\.\d+\.\d+$/ })} error={Boolean(form.formState.errors.minimumBrokerVersion)} helperText={form.formState.errors.minimumBrokerVersion ? 'Use a numeric version such as 3.0.0.' : 'Minimum compatible semantic version.'} /></Stack>{Object.keys(form.formState.errors).length > 0 && <Alert severity="error" tabIndex={-1} sx={{ mt: 2 }}>Application was not created. Correct the identified fields.</Alert>}{create.error && <ErrorState error={create.error} />}</DialogContent><DialogActions><Button onClick={() => { form.reset(); setOpen(false); }}>{t('cancel')}</Button><Button type="submit" variant="contained">{t('create')}</Button></DialogActions></form></Dialog></>;
}
